on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v5
      - run: mkdir release
      - name: Setup Java build
        run: |
          chmod +x android/gradlew
          echo "${{ secrets.ANDROID_KEYSTORE }}" > release.keystore.txt
          base64 -d release.keystore.txt > android/keystore
          echo "${{ secrets.ANDROID_KEYSTORE_PROPS }}" > release.keystore.props.txt
          base64 -d release.keystore.props.txt > android/keystore.properties
      - name: Release APKs
        run: |
          chmod +x scripts/android.sh && ./scripts/android.sh release ${{ inputs.version }}
          mv android/grim* release
      - uses: forgejo/upload-artifact@v4
        with:
          name: release_android
          path: release/*