name: Test build

on:
  push:
    tags-ignore:
      - "*"
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Check commit
        id: check
        run: |
          git fetch && git checkout master
          sha=$(git rev-parse HEAD)
          [[ "${{ github.sha }}" == "${sha}" ]] && test=false || test=true
          echo "test=${test}" >> "$FORGEJO_OUTPUT"
      - name: Build
        if: ${{ steps.check.outputs.test == 'true' }}
        run: cargo build --release
      - name: Telegram Notify Channel
        if: ${{ steps.check.outputs.test == 'true' && (success() || failure()) }}
        uses: actions/telegram-notifier@ardocrat
        with:
          api_url: ${{ secrets.TELEGRAM_API_URL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          status: ${{ job.status }}
          notify_fields: "actor,repository,workflow,branch,commit"
      - name: Telegram Notify Group
        if: ${{ steps.check.outputs.test == 'true' && (success() || failure()) }}
        uses: actions/telegram-notifier@ardocrat
        with:
          api_url: ${{ secrets.TELEGRAM_API_URL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_GROUP_ID }}
          status: ${{ job.status }}
          notify_fields: "actor,repository,workflow,branch,commit"