on:
  push:
    tags-ignore:
      - "*"
    branches-ignore:
      - master
      - ci

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build
        run: cargo build --release